name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:

  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "nodejs"
    
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn
      - uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Build Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Build Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Testes executados!"
      - uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Test Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Test Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Finalizado!"
      - uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Deploy Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Deploy Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

